/**
 * 颜文字图鉴 · Emoji 图标数据源（独立模块，与颜文字 data.js 区分）
 * 通过 window.KAOMOJI_ICONS 暴露给页面
 */
window.KAOMOJI_ICONS = {
    // 头部信息
    meta: {
        title: 'Emoji 图标库',
        icon: '😊',
        subtitle: '从笑脸到萌宠，从美食到出行 · 400+ 常用 Emoji 一目了然，点击即复制',
        totalLabel: '点击 复制',
        totalCount: 15
    },

    // 分类
    categories: [
        {
            "id": "face",
            "name": "表情 · 笑脸",
            "emoji": "😀",
            "badge": 41,
            "items": [
                { "symbol": "😀", "desc": "开心大笑" },
                { "symbol": "😁", "desc": "露齿笑" },
                { "symbol": "😂", "desc": "笑哭" },
                { "symbol": "🤣", "desc": "笑到打滚" },
                { "symbol": "😃", "desc": "咧嘴大笑" },
                { "symbol": "😄", "desc": "眯眯眼笑" },
                { "symbol": "😆", "desc": "大笑眯眼" },
                { "symbol": "😅", "desc": "尴尬汗笑" },
                { "symbol": "😊", "desc": "微笑脸红" },
                { "symbol": "😇", "desc": "天使微笑" },
                { "symbol": "🙂", "desc": "浅浅微笑" },
                { "symbol": "🙃", "desc": "倒脸微笑" },
                { "symbol": "😉", "desc": "眨眼" },
                { "symbol": "😌", "desc": "如释重负" },
                { "symbol": "😍", "desc": "花痴" },
                { "symbol": "🥰", "desc": "爱意满满" },
                { "symbol": "😘", "desc": "飞吻" },
                { "symbol": "😗", "desc": "亲亲" },
                { "symbol": "😙", "desc": "亲亲眨眼" },
                { "symbol": "😚", "desc": "嘟嘴亲亲" },
                { "symbol": "😋", "desc": "馋嘴" },
                { "symbol": "😜", "desc": "吐舌调皮" },
                { "symbol": "🤪", "desc": "搞怪鬼脸" },
                { "symbol": "😝", "desc": "吐舌眯眼" },
                { "symbol": "🤗", "desc": "拥抱" },
                { "symbol": "🤩", "desc": "星星眼" },
                { "symbol": "🥳", "desc": "庆祝" },
                { "symbol": "😸", "desc": "猫咪开心" },
                { "symbol": "😹", "desc": "猫咪笑哭" },
                { "symbol": "😺", "desc": "猫咪微笑" },
                { "symbol": "😏", "desc": "得意" },
                { "symbol": "🤨", "desc": "挑眉质疑" },
                { "symbol": "😒", "desc": "不满" },
                { "symbol": "😑", "desc": "面无表情" },
                { "symbol": "😶", "desc": "无语" },
                { "symbol": "🤐", "desc": "闭嘴" },
                { "symbol": "🤫", "desc": "嘘声" },
                { "symbol": "🫠", "desc": "融化瘫软" },
                { "symbol": "🥲", "desc": "含泪微笑" },
                { "symbol": "🤭", "desc": "捂嘴笑" },
                { "symbol": "🫢", "desc": "捂眼偷看" }
            ]
        },
        {
            "id": "shockface",
            "name": "表情 · 震惊尴尬",
            "emoji": "😳",
            "badge": 28,
            "items": [
                { "symbol": "😳", "desc": "脸红尴尬" },
                { "symbol": "😱", "desc": "吓到尖叫" },
                { "symbol": "😨", "desc": "惊慌" },
                { "symbol": "😰", "desc": "紧张冒汗" },
                { "symbol": "😥", "desc": "失落冒汗" },
                { "symbol": "😓", "desc": "无语汗" },
                { "symbol": "🤯", "desc": "大脑爆炸" },
                { "symbol": "😮", "desc": "惊讶张嘴" },
                { "symbol": "😲", "desc": "目瞪口呆" },
                { "symbol": "😯", "desc": "震惊沉默" },
                { "symbol": "🙄", "desc": "翻白眼" },
                { "symbol": "🤔", "desc": "思考" },
                { "symbol": "😬", "desc": "龇牙尴尬" },
                { "symbol": "😖", "desc": "纠结苦脸" },
                { "symbol": "😣", "desc": "痛苦坚持" },
                { "symbol": "😫", "desc": "疲惫抓狂" },
                { "symbol": "😩", "desc": "绝望叹脸" },
                { "symbol": "😢", "desc": "流泪" },
                { "symbol": "😭", "desc": "嚎啕大哭" },
                { "symbol": "🥺", "desc": "可怜巴巴" },
                { "symbol": "😠", "desc": "生气" },
                { "symbol": "😡", "desc": "红脸发怒" },
                { "symbol": "🤬", "desc": "怒骂" },
                { "symbol": "😤", "desc": "憋气" },
                { "symbol": "🥱", "desc": "打哈欠" },
                { "symbol": "😴", "desc": "睡觉" },
                { "symbol": "😷", "desc": "戴口罩" },
                { "symbol": "🤒", "desc": "发烧" }
            ]
        },
        {
            "id": "love",
            "name": "情感 · 爱心",
            "emoji": "❤️",
            "badge": 18,
            "items": [
                { "symbol": "❤️", "desc": "红心" },
                { "symbol": "🧡", "desc": "橙心" },
                { "symbol": "💛", "desc": "黄心" },
                { "symbol": "💚", "desc": "绿心" },
                { "symbol": "💙", "desc": "蓝心" },
                { "symbol": "💜", "desc": "紫心" },
                { "symbol": "🖤", "desc": "黑心" },
                { "symbol": "🤍", "desc": "白心" },
                { "symbol": "💖", "desc": "闪烁爱心" },
                { "symbol": "💗", "desc": "跳动粉心" },
                { "symbol": "💘", "desc": "射中心脏" },
                { "symbol": "💝", "desc": "礼盒爱心" },
                { "symbol": "💕", "desc": "两颗心" },
                { "symbol": "💞", "desc": "旋转爱心" },
                { "symbol": "💓", "desc": "跳动爱心" },
                { "symbol": "💟", "desc": "装饰爱心" },
                { "symbol": "❣️", "desc": "重叹爱心" },
                { "symbol": "💌", "desc": "情书" }
            ]
        },
        {
            "id": "gesture",
            "name": "手势 · 比赞",
            "emoji": "👍",
            "badge": 26,
            "items": [
                { "symbol": "👍", "desc": "点赞" },
                { "symbol": "👎", "desc": "点踩" },
                { "symbol": "👏", "desc": "鼓掌" },
                { "symbol": "🙌", "desc": "举手庆祝" },
                { "symbol": "🤝", "desc": "握手" },
                { "symbol": "👌", "desc": "OK" },
                { "symbol": "✌️", "desc": "剪刀手" },
                { "symbol": "🤞", "desc": "祈祷好运" },
                { "symbol": "🤟", "desc": "爱的手势" },
                { "symbol": "🤘", "desc": "摇滚手势" },
                { "symbol": "👊", "desc": "拳头碰拳" },
                { "symbol": "✊", "desc": "握拳加油" },
                { "symbol": "🤛", "desc": "左勾拳" },
                { "symbol": "🤜", "desc": "右勾拳" },
                { "symbol": "👋", "desc": "挥手" },
                { "symbol": "🤚", "desc": "举手" },
                { "symbol": "🖐️", "desc": "手掌张开" },
                { "symbol": "👈", "desc": "指向左边" },
                { "symbol": "👉", "desc": "指向右边" },
                { "symbol": "👆", "desc": "指向上方" },
                { "symbol": "👇", "desc": "指向下方" },
                { "symbol": "☝️", "desc": "食指朝上" },
                { "symbol": "🫶", "desc": "双手比心" },
                { "symbol": "🫰", "desc": "手指比心" },
                { "symbol": "🤌", "desc": "捏指手势" },
                { "symbol": "💪", "desc": "肌肉加油" }
            ]
        },
        {
            "id": "animal",
            "name": "动物 · 萌宠",
            "emoji": "🐶",
            "badge": 39,
            "items": [
                { "symbol": "🐶", "desc": "狗" },
                { "symbol": "🐱", "desc": "猫" },
                { "symbol": "🐭", "desc": "鼠" },
                { "symbol": "🐹", "desc": "仓鼠" },
                { "symbol": "🐰", "desc": "兔子" },
                { "symbol": "🦊", "desc": "狐狸" },
                { "symbol": "🐻", "desc": "熊" },
                { "symbol": "🐼", "desc": "熊猫" },
                { "symbol": "🐨", "desc": "考拉" },
                { "symbol": "🐯", "desc": "老虎" },
                { "symbol": "🦁", "desc": "狮子" },
                { "symbol": "🐮", "desc": "牛" },
                { "symbol": "🐷", "desc": "猪" },
                { "symbol": "🐸", "desc": "青蛙" },
                { "symbol": "🐵", "desc": "猴子" },
                { "symbol": "🦄", "desc": "独角兽" },
                { "symbol": "🐣", "desc": "破壳小鸡" },
                { "symbol": "🐤", "desc": "小鸡" },
                { "symbol": "🐦", "desc": "小鸟" },
                { "symbol": "🦆", "desc": "鸭子" },
                { "symbol": "🦅", "desc": "老鹰" },
                { "symbol": "🦉", "desc": "猫头鹰" },
                { "symbol": "🐺", "desc": "狼" },
                { "symbol": "🦝", "desc": "浣熊" },
                { "symbol": "🐴", "desc": "马" },
                { "symbol": "🐑", "desc": "绵羊" },
                { "symbol": "🐘", "desc": "大象" },
                { "symbol": "🦓", "desc": "斑马" },
                { "symbol": "🦍", "desc": "大猩猩" },
                { "symbol": "🐢", "desc": "乌龟" },
                { "symbol": "🐍", "desc": "蛇" },
                { "symbol": "🐙", "desc": "章鱼" },
                { "symbol": "🦞", "desc": "龙虾" },
                { "symbol": "🦀", "desc": "螃蟹" },
                { "symbol": "🐳", "desc": "鲸鱼" },
                { "symbol": "🐬", "desc": "海豚" },
                { "symbol": "🐟", "desc": "鱼" },
                { "symbol": "🦈", "desc": "鲨鱼" },
                { "symbol": "🦋", "desc": "蝴蝶" }
            ]
        },
        {
            "id": "food",
            "name": "美食 · 吃喝",
            "emoji": "🍔",
            "badge": 48,
            "items": [
                { "symbol": "🍔", "desc": "汉堡" },
                { "symbol": "🍟", "desc": "薯条" },
                { "symbol": "🍕", "desc": "披萨" },
                { "symbol": "🍜", "desc": "拉面" },
                { "symbol": "🍣", "desc": "寿司" },
                { "symbol": "🍰", "desc": "蛋糕" },
                { "symbol": "🍩", "desc": "甜甜圈" },
                { "symbol": "🍪", "desc": "曲奇" },
                { "symbol": "🍦", "desc": "冰淇淋" },
                { "symbol": "🍺", "desc": "啤酒" },
                { "symbol": "🍵", "desc": "绿茶" },
                { "symbol": "☕", "desc": "咖啡" },
                { "symbol": "🍎", "desc": "苹果" },
                { "symbol": "🍉", "desc": "西瓜" },
                { "symbol": "🍇", "desc": "葡萄" },
                { "symbol": "🍓", "desc": "草莓" },
                { "symbol": "🥟", "desc": "饺子" },
                { "symbol": "🍤", "desc": "炸虾" },
                { "symbol": "🍝", "desc": "意面" },
                { "symbol": "🍛", "desc": "咖喱饭" },
                { "symbol": "🍲", "desc": "火锅" },
                { "symbol": "🥗", "desc": "沙拉" },
                { "symbol": "🥤", "desc": "奶茶杯" },
                { "symbol": "🍭", "desc": "棒棒糖" },
                { "symbol": "🍱", "desc": "便当" },
                { "symbol": "🍙", "desc": "饭团" },
                { "symbol": "🍫", "desc": "巧克力" },
                { "symbol": "🍿", "desc": "爆米花" },
                { "symbol": "🥞", "desc": "松饼" },
                { "symbol": "🥐", "desc": "牛角包" },
                { "symbol": "🍞", "desc": "面包" },
                { "symbol": "🍌", "desc": "香蕉" },
                { "symbol": "🍊", "desc": "橙子" },
                { "symbol": "🍑", "desc": "桃子" },
                { "symbol": "🍒", "desc": "樱桃" },
                { "symbol": "🥥", "desc": "椰子" },
                { "symbol": "🥑", "desc": "牛油果" },
                { "symbol": "🌽", "desc": "玉米" },
                { "symbol": "🍆", "desc": "茄子" },
                { "symbol": "🍏", "desc": "青苹果" },
                { "symbol": "🍐", "desc": "梨" },
                { "symbol": "🍋", "desc": "柠檬" },
                { "symbol": "🍈", "desc": "甜瓜" },
                { "symbol": "🍍", "desc": "菠萝" },
                { "symbol": "🥭", "desc": "芒果" },
                { "symbol": "🥝", "desc": "猕猴桃" },
                { "symbol": "🫐", "desc": "蓝莓" },
                { "symbol": "🍅", "desc": "番茄" }
            ]
        },
        {
            "id": "activity",
            "name": "运动 · 活动",
            "emoji": "⚽",
            "badge": 27,
            "items": [
                { "symbol": "⚽", "desc": "足球" },
                { "symbol": "🏀", "desc": "篮球" },
                { "symbol": "🏈", "desc": "橄榄球" },
                { "symbol": "🎾", "desc": "网球" },
                { "symbol": "🏐", "desc": "排球" },
                { "symbol": "🎱", "desc": "台球" },
                { "symbol": "🏓", "desc": "乒乓球" },
                { "symbol": "🏸", "desc": "羽毛球" },
                { "symbol": "🎮", "desc": "游戏手柄" },
                { "symbol": "🎲", "desc": "骰子" },
                { "symbol": "🎯", "desc": "靶心" },
                { "symbol": "🏆", "desc": "奖杯" },
                { "symbol": "🏃", "desc": "跑步" },
                { "symbol": "🏊", "desc": "游泳" },
                { "symbol": "🚴", "desc": "骑行" },
                { "symbol": "🧗", "desc": "攀岩" },
                { "symbol": "🥊", "desc": "拳击" },
                { "symbol": "🥋", "desc": "武术" },
                { "symbol": "🎿", "desc": "滑雪" },
                { "symbol": "🛹", "desc": "滑板" },
                { "symbol": "🎳", "desc": "保龄球" },
                { "symbol": "🥇", "desc": "金牌" },
                { "symbol": "🥈", "desc": "银牌" },
                { "symbol": "🥉", "desc": "铜牌" },
                { "symbol": "🧩", "desc": "拼图" },
                { "symbol": "🎨", "desc": "调色板" },
                { "symbol": "🎭", "desc": "面具" }
            ]
        },
        {
            "id": "music",
            "name": "乐器 · 音乐",
            "emoji": "🎵",
            "badge": 18,
            "items": [
                { "symbol": "🎵", "desc": "音符" },
                { "symbol": "🎶", "desc": "音符串" },
                { "symbol": "🎤", "desc": "麦克风" },
                { "symbol": "🎧", "desc": "耳机" },
                { "symbol": "🎸", "desc": "吉他" },
                { "symbol": "🎹", "desc": "钢琴" },
                { "symbol": "🥁", "desc": "鼓" },
                { "symbol": "🎷", "desc": "萨克斯" },
                { "symbol": "🎺", "desc": "小号" },
                { "symbol": "🎻", "desc": "小提琴" },
                { "symbol": "🪕", "desc": "班卓琴" },
                { "symbol": "🪗", "desc": "手风琴" },
                { "symbol": "🪈", "desc": "长笛" },
                { "symbol": "🪘", "desc": "非洲鼓" },
                { "symbol": "🎙️", "desc": "录音麦克风" },
                { "symbol": "🎚️", "desc": "调音滑块" },
                { "symbol": "🎛️", "desc": "调音台" },
                { "symbol": "📻", "desc": "收音机" }
            ]
        },
        {
            "id": "nature",
            "name": "自然 · 天气",
            "emoji": "🌈",
            "badge": 28,
            "items": [
                { "symbol": "🌈", "desc": "彩虹" },
                { "symbol": "☀️", "desc": "晴天" },
                { "symbol": "⛅", "desc": "多云" },
                { "symbol": "🌧️", "desc": "下雨" },
                { "symbol": "⛈️", "desc": "雷雨" },
                { "symbol": "❄️", "desc": "雪花" },
                { "symbol": "🌊", "desc": "海浪" },
                { "symbol": "🌙", "desc": "月亮" },
                { "symbol": "⭐", "desc": "星星" },
                { "symbol": "🌻", "desc": "向日葵" },
                { "symbol": "🌸", "desc": "樱花" },
                { "symbol": "🍀", "desc": "四叶草" },
                { "symbol": "🌤️", "desc": "晴间云" },
                { "symbol": "🌦️", "desc": "晴时雨" },
                { "symbol": "🌪️", "desc": "龙卷风" },
                { "symbol": "🌋", "desc": "火山" },
                { "symbol": "🌵", "desc": "仙人掌" },
                { "symbol": "🌴", "desc": "棕榈树" },
                { "symbol": "🌲", "desc": "松树" },
                { "symbol": "🍁", "desc": "枫叶" },
                { "symbol": "🌹", "desc": "玫瑰" },
                { "symbol": "🌺", "desc": "芙蓉" },
                { "symbol": "🌷", "desc": "郁金香" },
                { "symbol": "🌼", "desc": "雏菊" },
                { "symbol": "🍃", "desc": "树叶" },
                { "symbol": "🍂", "desc": "落叶" },
                { "symbol": "🍄", "desc": "蘑菇" },
                { "symbol": "☘️", "desc": "三叶草" }
            ]
        },
        {
            "id": "symbol",
            "name": "符号 · 标记",
            "emoji": "⭐",
            "badge": 26,
            "items": [
                { "symbol": "⭐", "desc": "星星" },
                { "symbol": "✨", "desc": "闪光" },
                { "symbol": "🔥", "desc": "火" },
                { "symbol": "💧", "desc": "水滴" },
                { "symbol": "⚡", "desc": "闪电" },
                { "symbol": "🎵", "desc": "音符" },
                { "symbol": "💯", "desc": "满分" },
                { "symbol": "❗", "desc": "感叹号" },
                { "symbol": "❓", "desc": "问号" },
                { "symbol": "✅", "desc": "对勾" },
                { "symbol": "❌", "desc": "叉号" },
                { "symbol": "⚠️", "desc": "警告" },
                { "symbol": "🚫", "desc": "禁止" },
                { "symbol": "⛔", "desc": "禁行" },
                { "symbol": "♻️", "desc": "循环回收" },
                { "symbol": "☑️", "desc": "勾选框" },
                { "symbol": "➡️", "desc": "向右箭头" },
                { "symbol": "⬅️", "desc": "向左箭头" },
                { "symbol": "🔁", "desc": "循环箭头" },
                { "symbol": "💤", "desc": "睡觉" },
                { "symbol": "👀", "desc": "眼睛" },
                { "symbol": "💬", "desc": "对话气泡" },
                { "symbol": "💭", "desc": "思考气泡" },
                { "symbol": "💡", "desc": "灵感" },
                { "symbol": "💢", "desc": "怒气" },
                { "symbol": "💦", "desc": "汗滴" }
            ]
        },
        {
            "id": "celebration",
            "name": "庆祝 · 场景",
            "emoji": "🎉",
            "badge": 16,
            "items": [
                { "symbol": "🎉", "desc": "庆祝彩带" },
                { "symbol": "🎊", "desc": "庆祝礼花" },
                { "symbol": "🎂", "desc": "生日蛋糕" },
                { "symbol": "🎁", "desc": "礼物" },
                { "symbol": "🎈", "desc": "气球" },
                { "symbol": "🥂", "desc": "干杯" },
                { "symbol": "🍾", "desc": "香槟" },
                { "symbol": "🏮", "desc": "红灯笼" },
                { "symbol": "🧨", "desc": "鞭炮" },
                { "symbol": "💐", "desc": "花束" },
                { "symbol": "🎆", "desc": "烟花" },
                { "symbol": "🎇", "desc": "烟花棒" },
                { "symbol": "🎃", "desc": "南瓜灯" },
                { "symbol": "🎄", "desc": "圣诞树" },
                { "symbol": "🎅", "desc": "圣诞老人" },
                { "symbol": "🎓", "desc": "毕业帽" }
            ]
        },
        {
            "id": "people",
            "name": "职业 · 人物",
            "emoji": "👩",
            "badge": 20,
            "items": [
                { "symbol": "👶", "desc": "宝宝" },
                { "symbol": "👧", "desc": "小女孩" },
                { "symbol": "👦", "desc": "小男孩" },
                { "symbol": "👩", "desc": "女人" },
                { "symbol": "👨", "desc": "男人" },
                { "symbol": "👵", "desc": "老奶奶" },
                { "symbol": "👴", "desc": "老爷爷" },
                { "symbol": "🧑", "desc": "成人" },
                { "symbol": "👮", "desc": "警察" },
                { "symbol": "🕵️", "desc": "侦探" },
                { "symbol": "💂", "desc": "卫兵" },
                { "symbol": "👷", "desc": "建筑工人" },
                { "symbol": "👩⚕️", "desc": "女医生" },
                { "symbol": "👨⚕️", "desc": "男医生" },
                { "symbol": "👩🎓", "desc": "女学生" },
                { "symbol": "👨🎓", "desc": "男学生" },
                { "symbol": "👩🏫", "desc": "女老师" },
                { "symbol": "👨🏫", "desc": "男老师" },
                { "symbol": "👩💻", "desc": "女程序员" },
                { "symbol": "👨💻", "desc": "男程序员" }
            ]
        },
        {
            "id": "travel",
            "name": "出行 · 交通",
            "emoji": "🚗",
            "badge": 32,
            "items": [
                { "symbol": "🚗", "desc": "轿车" },
                { "symbol": "🚕", "desc": "出租车" },
                { "symbol": "🚌", "desc": "公交车" },
                { "symbol": "🚎", "desc": "有轨电车" },
                { "symbol": "🚓", "desc": "警车" },
                { "symbol": "🚑", "desc": "救护车" },
                { "symbol": "🚒", "desc": "消防车" },
                { "symbol": "🚚", "desc": "货车" },
                { "symbol": "🚙", "desc": "越野车" },
                { "symbol": "🚲", "desc": "自行车" },
                { "symbol": "🛵", "desc": "电动车" },
                { "symbol": "🏍️", "desc": "摩托车" },
                { "symbol": "✈️", "desc": "飞机" },
                { "symbol": "🚀", "desc": "火箭" },
                { "symbol": "🚁", "desc": "直升机" },
                { "symbol": "🚢", "desc": "轮船" },
                { "symbol": "⛵", "desc": "帆船" },
                { "symbol": "🚉", "desc": "车站" },
                { "symbol": "🚏", "desc": "公交站" },
                { "symbol": "🛩️", "desc": "小型飞机" },
                { "symbol": "🚆", "desc": "火车" },
                { "symbol": "🚄", "desc": "高铁" },
                { "symbol": "🚅", "desc": "子弹头列车" },
                { "symbol": "🚝", "desc": "单轨列车" },
                { "symbol": "🚃", "desc": "电车" },
                { "symbol": "🚇", "desc": "地铁" },
                { "symbol": "🛴", "desc": "滑板车" },
                { "symbol": "🛻", "desc": "皮卡" },
                { "symbol": "🛸", "desc": "飞碟" },
                { "symbol": "🚡", "desc": "缆车" },
                { "symbol": "🛶", "desc": "独木舟" },
                { "symbol": "🚦", "desc": "红绿灯" }
            ]
        },
        {
            "id": "place",
            "name": "建筑 · 地点",
            "emoji": "🏠",
            "badge": 16,
            "items": [
                { "symbol": "🏠", "desc": "房子" },
                { "symbol": "🏡", "desc": "带花园小屋" },
                { "symbol": "🏢", "desc": "办公楼" },
                { "symbol": "🏫", "desc": "学校" },
                { "symbol": "🏥", "desc": "医院" },
                { "symbol": "🏦", "desc": "银行" },
                { "symbol": "🏪", "desc": "便利店" },
                { "symbol": "🏨", "desc": "酒店" },
                { "symbol": "🏬", "desc": "百货商场" },
                { "symbol": "🏯", "desc": "日式城堡" },
                { "symbol": "🏰", "desc": "欧式城堡" },
                { "symbol": "⛪", "desc": "教堂" },
                { "symbol": "🕌", "desc": "清真寺" },
                { "symbol": "🏛️", "desc": "古典建筑" },
                { "symbol": "🗽", "desc": "自由女神像" },
                { "symbol": "🗼", "desc": "东京铁塔" }
            ]
        },
        {
            "id": "life",
            "name": "生活 · 物品",
            "emoji": "📱",
            "badge": 30,
            "items": [
                { "symbol": "📱", "desc": "手机" },
                { "symbol": "💻", "desc": "笔记本电脑" },
                { "symbol": "⌚", "desc": "手表" },
                { "symbol": "💡", "desc": "灯泡" },
                { "symbol": "🔑", "desc": "钥匙" },
                { "symbol": "🔧", "desc": "扳手" },
                { "symbol": "🔨", "desc": "锤子" },
                { "symbol": "⚙️", "desc": "齿轮" },
                { "symbol": "📦", "desc": "包裹" },
                { "symbol": "🎒", "desc": "书包" },
                { "symbol": "👕", "desc": "T恤" },
                { "symbol": "👖", "desc": "牛仔裤" },
                { "symbol": "👗", "desc": "连衣裙" },
                { "symbol": "👔", "desc": "领带衬衫" },
                { "symbol": "👑", "desc": "皇冠" },
                { "symbol": "🎩", "desc": "礼帽" },
                { "symbol": "👒", "desc": "女帽" },
                { "symbol": "💍", "desc": "戒指" },
                { "symbol": "👜", "desc": "手提包" },
                { "symbol": "👟", "desc": "运动鞋" },
                { "symbol": "📷", "desc": "相机" },
                { "symbol": "📹", "desc": "摄像机" },
                { "symbol": "📞", "desc": "电话" },
                { "symbol": "📻", "desc": "收音机" },
                { "symbol": "🖥️", "desc": "台式电脑" },
                { "symbol": "🖨️", "desc": "打印机" },
                { "symbol": "⌨️", "desc": "键盘" },
                { "symbol": "🔒", "desc": "上锁" },
                { "symbol": "🔓", "desc": "开锁" },
                { "symbol": "🔍", "desc": "放大镜" }
            ]
        }
    ],

    // 底部 4 个特性卡
    features: [
        {
            "icon": "📋",
            "iconClass": "feat-blue",
            "title": "一键复制",
            "desc": "点击任意 Emoji 即可复制到剪贴板"
        },
        {
            "icon": "🔍",
            "iconClass": "feat-green",
            "title": "分类清晰",
            "desc": "分类精心整理 快速找到想要的表情"
        },
        {
            "icon": "⭐",
            "iconClass": "feat-purple",
            "title": "持续更新",
            "desc": "更多 Emoji 持续收录中 欢迎收藏本站"
        },
        {
            "icon": "❤️",
            "iconClass": "feat-orange",
            "title": "轻松使用",
            "desc": "简洁界面，无需学习 让表达更有趣"
        }
    ],

    // 页脚
    footer: 'Emoji 图标库 · 让表达更有趣'
};
