/**
 * 颜文字图鉴 · 汉字部首数据源（独立模块，与颜文字 data.js、图标 icons.js、特殊符号 symbols.js 区分）
 * 收录《康熙字典》传统 214 部首，按构字位置分类，每类内部按笔画升序排列
 * 通过 window.KAOMOJI_RADICALS 暴露给页面
 */
window.KAOMOJI_RADICALS = {
    // 头部信息
    meta: {
        title: '汉字部首',
        icon: '艹',
        subtitle: '康熙字典 214 部首 · 按位置·笔画分类',
        totalLabel: '点击 复制',
        totalCount: 6
    },

    // 分类（按构字位置，每部首唯一归属；每类内部按笔画升序）
    categories: [
        {
            "id": "radical-left",
            "name": "左偏旁",
            "emoji": "亻",
            "badge": 24,
            "items": [
                { "symbol": "人", "desc": "单人旁（rén）" },
                { "symbol": "土", "desc": "提土旁（tǔ）" },
                { "symbol": "女", "desc": "女字旁（nǚ）" },
                { "symbol": "子", "desc": "子字旁（zǐ）" },
                { "symbol": "口", "desc": "口字旁（kǒu）" },
                { "symbol": "心", "desc": "竖心旁（xīn）" },
                { "symbol": "手", "desc": "提手旁（shǒu）" },
                { "symbol": "水", "desc": "三点水（shuǐ）" },
                { "symbol": "火", "desc": "火字旁（huǒ）" },
                { "symbol": "日", "desc": "日字旁（rì）" },
                { "symbol": "月", "desc": "月字旁（yuè）" },
                { "symbol": "木", "desc": "木字旁（mù）" },
                { "symbol": "牛", "desc": "牛字旁（niú）" },
                { "symbol": "玉", "desc": "王字旁（yù）" },
                { "symbol": "石", "desc": "石字旁（shí）" },
                { "symbol": "禾", "desc": "禾木旁（hé）" },
                { "symbol": "耳", "desc": "耳字旁（ěr）" },
                { "symbol": "虫", "desc": "虫字旁（chóng）" },
                { "symbol": "米", "desc": "米字旁（mǐ）" },
                { "symbol": "車", "desc": "车字旁（chē）" },
                { "symbol": "金", "desc": "金字旁（jīn）" },
                { "symbol": "馬", "desc": "马字旁（mǎ）" },
                { "symbol": "魚", "desc": "鱼字旁（yú）" },
                { "symbol": "鳥", "desc": "鸟字旁（niǎo）" }
            ]
        },
        {
            "id": "radical-right",
            "name": "右偏旁",
            "emoji": "刂",
            "badge": 14,
            "items": [
                { "symbol": "刀", "desc": "立刀旁（dāo）" },
                { "symbol": "力", "desc": "力字旁（lì）" },
                { "symbol": "又", "desc": "又字旁（yòu）" },
                { "symbol": "攴", "desc": "攴字旁（pū）" },
                { "symbol": "殳", "desc": "殳字旁（shū）" },
                { "symbol": "欠", "desc": "欠字旁（qiàn）" },
                { "symbol": "辛", "desc": "辛字旁（xīn）" },
                { "symbol": "見", "desc": "见字旁（jiàn）" },
                { "symbol": "貝", "desc": "贝字旁（bèi）" },
                { "symbol": "邑", "desc": "右耳旁（yì）" },
                { "symbol": "隹", "desc": "隹字旁（zhuī）" },
                { "symbol": "長", "desc": "长字旁（cháng）" },
                { "symbol": "阜", "desc": "右耳旁（fù）" },
                { "symbol": "頁", "desc": "页字旁（yè）" }
            ]
        },
        {
            "id": "radical-top",
            "name": "字头",
            "emoji": "艹",
            "badge": 18,
            "items": [
                { "symbol": "冖", "desc": "秃宝盖（mì）" },
                { "symbol": "冫", "desc": "两点水（bīng）" },
                { "symbol": "大", "desc": "大字头（dà）" },
                { "symbol": "山", "desc": "山字头（shān）" },
                { "symbol": "尸", "desc": "尸字头（shī）" },
                { "symbol": "广", "desc": "广字头（guǎng）" },
                { "symbol": "宀", "desc": "宝盖头（mián）" },
                { "symbol": "尢", "desc": "尤字头（wāng）" },
                { "symbol": "父", "desc": "父字头（fù）" },
                { "symbol": "戶", "desc": "户字头（hù）" },
                { "symbol": "爪", "desc": "爪字头（zhǎo）" },
                { "symbol": "穴", "desc": "穴字头（xué）" },
                { "symbol": "疒", "desc": "病字头（nè）" },
                { "symbol": "癶", "desc": "登字头（bō）" },
                { "symbol": "竹", "desc": "竹字头（zhú）" },
                { "symbol": "虍", "desc": "虎字头（hǔ）" },
                { "symbol": "艸", "desc": "草字头（cǎo）" },
                { "symbol": "雨", "desc": "雨字头（yǔ）" }
            ]
        },
        {
            "id": "radical-bottom",
            "name": "字底",
            "emoji": "灬",
            "badge": 13,
            "items": [
                { "symbol": "儿", "desc": "儿字底（ér）" },
                { "symbol": "廾", "desc": "弄字底（gǒng）" },
                { "symbol": "巛", "desc": "川字底（chuān）" },
                { "symbol": "灬", "desc": "四点底（biāo）" },
                { "symbol": "冃", "desc": "冃字底（mào）" },
                { "symbol": "皿", "desc": "皿字底（mǐn）" },
                { "symbol": "衣", "desc": "衣字底（yī）" },
                { "symbol": "血", "desc": "血字底（xuè）" },
                { "symbol": "至", "desc": "至字底（zhì）" },
                { "symbol": "臼", "desc": "臼字底（jiù）" },
                { "symbol": "糸", "desc": "系字底（mì）" },
                { "symbol": "辵", "desc": "走之底（chuò）" },
                { "symbol": "黑", "desc": "黑字底（hēi）" }
            ]
        },
        {
            "id": "radical-frame",
            "name": "包围结构",
            "emoji": "囗",
            "badge": 10,
            "items": [
                { "symbol": "冂", "desc": "同字框（jiōng）" },
                { "symbol": "匚", "desc": "区字框（fāng）" },
                { "symbol": "匸", "desc": "匸字框（xì）" },
                { "symbol": "凵", "desc": "凵字框（kǎn）" },
                { "symbol": "厂", "desc": "厂字框（hǎn）" },
                { "symbol": "囗", "desc": "国字框（wéi）" },
                { "symbol": "弋", "desc": "弋字框（yì）" },
                { "symbol": "用", "desc": "用字框（yòng）" },
                { "symbol": "門", "desc": "门字框（mén）" },
                { "symbol": "風", "desc": "风字框（fēng）" }
            ]
        },
        {
            "id": "radical-single",
            "name": "独体单字",
            "emoji": "一",
            "badge": 137,
            "items": [
                { "symbol": "一", "desc": "一（yī）" },
                { "symbol": "丨", "desc": "竖（gǔn）" },
                { "symbol": "丶", "desc": "点（zhǔ）" },
                { "symbol": "丿", "desc": "撇（piě）" },
                { "symbol": "乙", "desc": "乙（yǐ）" },
                { "symbol": "亅", "desc": "竖钩（jué）" },
                { "symbol": "二", "desc": "二（èr）" },
                { "symbol": "亠", "desc": "京字头（tóu）" },
                { "symbol": "入", "desc": "入（rù）" },
                { "symbol": "八", "desc": "八（bā）" },
                { "symbol": "几", "desc": "几（jǐ）" },
                { "symbol": "勹", "desc": "包字头（bāo）" },
                { "symbol": "匕", "desc": "匕（bǐ）" },
                { "symbol": "十", "desc": "十（shí）" },
                { "symbol": "卜", "desc": "卜（bǔ）" },
                { "symbol": "卩", "desc": "单耳旁（jié）" },
                { "symbol": "厶", "desc": "私字旁（sī）" },
                { "symbol": "士", "desc": "士（shì）" },
                { "symbol": "夂", "desc": "折文（zhǐ）" },
                { "symbol": "夊", "desc": "夊（suī）" },
                { "symbol": "夕", "desc": "夕（xī）" },
                { "symbol": "寸", "desc": "寸（cùn）" },
                { "symbol": "小", "desc": "小（xiǎo）" },
                { "symbol": "屮", "desc": "屮（chè）" },
                { "symbol": "工", "desc": "工（gōng）" },
                { "symbol": "己", "desc": "己（jǐ）" },
                { "symbol": "巾", "desc": "巾（jīn）" },
                { "symbol": "干", "desc": "干（gān）" },
                { "symbol": "幺", "desc": "幺（yāo）" },
                { "symbol": "廴", "desc": "建字旁（yǐn）" },
                { "symbol": "弓", "desc": "弓（gōng）" },
                { "symbol": "彐", "desc": "彐（jì）" },
                { "symbol": "彡", "desc": "三撇（shān）" },
                { "symbol": "彳", "desc": "双人旁（chì）" },
                { "symbol": "戈", "desc": "戈（gē）" },
                { "symbol": "支", "desc": "支（zhī）" },
                { "symbol": "文", "desc": "文（wén）" },
                { "symbol": "斗", "desc": "斗（dǒu）" },
                { "symbol": "斤", "desc": "斤（jīn）" },
                { "symbol": "方", "desc": "方（fāng）" },
                { "symbol": "无", "desc": "无（wú）" },
                { "symbol": "曰", "desc": "曰（yuē）" },
                { "symbol": "止", "desc": "止（zhǐ）" },
                { "symbol": "歹", "desc": "歹（dǎi）" },
                { "symbol": "毋", "desc": "毋（wú）" },
                { "symbol": "比", "desc": "比（bǐ）" },
                { "symbol": "毛", "desc": "毛（máo）" },
                { "symbol": "氏", "desc": "氏（shì）" },
                { "symbol": "气", "desc": "气（qì）" },
                { "symbol": "爻", "desc": "爻（yáo）" },
                { "symbol": "爿", "desc": "爿（pán）" },
                { "symbol": "片", "desc": "片（piàn）" },
                { "symbol": "牙", "desc": "牙（yá）" },
                { "symbol": "犬", "desc": "反犬旁（quǎn）" },
                { "symbol": "玄", "desc": "玄（xuán）" },
                { "symbol": "瓜", "desc": "瓜（guā）" },
                { "symbol": "瓦", "desc": "瓦（wǎ）" },
                { "symbol": "甘", "desc": "甘（gān）" },
                { "symbol": "生", "desc": "生（shēng）" },
                { "symbol": "田", "desc": "田（tián）" },
                { "symbol": "疋", "desc": "疋（pǐ）" },
                { "symbol": "白", "desc": "白（bái）" },
                { "symbol": "皮", "desc": "皮（pí）" },
                { "symbol": "目", "desc": "目（mù）" },
                { "symbol": "矛", "desc": "矛（máo）" },
                { "symbol": "矢", "desc": "矢（shǐ）" },
                { "symbol": "示", "desc": "示（shì）" },
                { "symbol": "禸", "desc": "禸（róu）" },
                { "symbol": "立", "desc": "立（lì）" },
                { "symbol": "缶", "desc": "缶（fǒu）" },
                { "symbol": "网", "desc": "网（wǎng）" },
                { "symbol": "羊", "desc": "羊（yáng）" },
                { "symbol": "羽", "desc": "羽（yǔ）" },
                { "symbol": "老", "desc": "老（lǎo）" },
                { "symbol": "而", "desc": "而（ér）" },
                { "symbol": "耒", "desc": "耒（lěi）" },
                { "symbol": "聿", "desc": "聿（yù）" },
                { "symbol": "肉", "desc": "肉（ròu）" },
                { "symbol": "臣", "desc": "臣（chén）" },
                { "symbol": "自", "desc": "自（zì）" },
                { "symbol": "舌", "desc": "舌（shé）" },
                { "symbol": "舛", "desc": "舛（chuǎn）" },
                { "symbol": "舟", "desc": "舟（zhōu）" },
                { "symbol": "艮", "desc": "艮（gèn）" },
                { "symbol": "色", "desc": "色（sè）" },
                { "symbol": "行", "desc": "行（xíng）" },
                { "symbol": "襾", "desc": "襾（yà）" },
                { "symbol": "角", "desc": "角（jiǎo）" },
                { "symbol": "言", "desc": "言（yán）" },
                { "symbol": "谷", "desc": "谷（gǔ）" },
                { "symbol": "豆", "desc": "豆（dòu）" },
                { "symbol": "豕", "desc": "豕（shǐ）" },
                { "symbol": "豸", "desc": "豸（zhì）" },
                { "symbol": "赤", "desc": "赤（chì）" },
                { "symbol": "走", "desc": "走（zǒu）" },
                { "symbol": "足", "desc": "足（zú）" },
                { "symbol": "身", "desc": "身（shēn）" },
                { "symbol": "辰", "desc": "辰（chén）" },
                { "symbol": "酉", "desc": "酉（yǒu）" },
                { "symbol": "釆", "desc": "釆（biàn）" },
                { "symbol": "里", "desc": "里（lǐ）" },
                { "symbol": "隶", "desc": "隶（dài）" },
                { "symbol": "靑", "desc": "青（qīng）" },
                { "symbol": "非", "desc": "非（fēi）" },
                { "symbol": "面", "desc": "面（miàn）" },
                { "symbol": "革", "desc": "革（gé）" },
                { "symbol": "韋", "desc": "韦（wéi）" },
                { "symbol": "韭", "desc": "韭（jiǔ）" },
                { "symbol": "音", "desc": "音（yīn）" },
                { "symbol": "飛", "desc": "飞（fēi）" },
                { "symbol": "食", "desc": "食（shí）" },
                { "symbol": "首", "desc": "首（shǒu）" },
                { "symbol": "香", "desc": "香（xiāng）" },
                { "symbol": "骨", "desc": "骨（gǔ）" },
                { "symbol": "鬼", "desc": "鬼（guǐ）" },
                { "symbol": "高", "desc": "高（gāo）" },
                { "symbol": "髟", "desc": "髟（biāo）" },
                { "symbol": "鬥", "desc": "斗（dòu）" },
                { "symbol": "鬯", "desc": "鬯（chàng）" },
                { "symbol": "鬲", "desc": "鬲（lì）" },
                { "symbol": "鹵", "desc": "卤（lǔ）" },
                { "symbol": "鹿", "desc": "鹿（lù）" },
                { "symbol": "麥", "desc": "麦（mài）" },
                { "symbol": "麻", "desc": "麻（má）" },
                { "symbol": "黃", "desc": "黄（huáng）" },
                { "symbol": "黍", "desc": "黍（shǔ）" },
                { "symbol": "黹", "desc": "黹（zhǐ）" },
                { "symbol": "黽", "desc": "黾（mǐn）" },
                { "symbol": "鼎", "desc": "鼎（dǐng）" },
                { "symbol": "鼓", "desc": "鼓（gǔ）" },
                { "symbol": "鼠", "desc": "鼠（shǔ）" },
                { "symbol": "鼻", "desc": "鼻（bí）" },
                { "symbol": "齊", "desc": "齐（qí）" },
                { "symbol": "齒", "desc": "齿（chǐ）" },
                { "symbol": "龍", "desc": "龙（lóng）" },
                { "symbol": "龜", "desc": "龟（guī）" },
                { "symbol": "龠", "desc": "龠（yuè）" }
            ]
        }
    ],

    // 底部 4 个特性卡
    features: [
        {
            "icon": "📋",
            "iconClass": "feat-blue",
            "title": "一键复制",
            "desc": "点击任意部首即可复制到剪贴板"
        },
        {
            "icon": "📚",
            "iconClass": "feat-green",
            "title": "传统 214 部",
            "desc": "依康熙字典完整收录 按位置·笔画分类"
        },
        {
            "icon": "⭐",
            "iconClass": "feat-purple",
            "title": "持续更新",
            "desc": "更多部首持续收录中 欢迎收藏本站"
        },
        {
            "icon": "❤️",
            "iconClass": "feat-orange",
            "title": "轻松使用",
            "desc": "简洁界面，无需学习 常用部首轻松获取"
        }
    ]
};
